export const CREATE_NOTE = 'CREATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const CREATE_TODO = 'CREATE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const DELETE_TODO = 'DELETE_TODO';

export const CHANGE_VALUES_FORM_NOTE = 'CHANGE_VALUES_FORM_NOTE';
export const CHANGE_VALUES_FORM_TODO = 'CHANGE_VALUES_FORM_TODO';
export const CHANGE_OPENNESS_FORM_NOTE = 'CHANGE_OPENNESS_FORM_NOTE';
export const CHANGE_OPENNESS_FORM_TODO = 'CHANGE_OPENNESS_FORM_TODO';

export const CHANGE_ACTIVE_BURGER = 'CHANGE_ACTIVE_BURGER';


