export const CREATE_NOTE = 'CREATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const CHANGE_VALUES_FORM = 'CHANGE_VALUES_FORM';
export const CHANGE_OPENNESS_FORM = 'CHANGE_OPENNESS_FORM';

export const CHANGE_ACTIVE_BURGER = 'CHANGE_ACTIVE_BURGER';


